[window]
dimensions    = { columns = 90, lines = 30 }
padding       = { x = 10, y = 10 }
option_as_alt = "Both"

[font]
normal        = { family = "Iosevka Term", style = "Regular" }
bold          = { family = "Iosevka Term", style = "Bold" }
italic        = { family = "Iosevka Term", style = "Italic" }
bold_italic   = { family = "Iosevka Term", style = "Bold Italic" }
size          = 14

[colors]
cursor    = { text = "#21084a", cursor = "#ff2603" }
selection = { text = "#21084a", cursor = "#ff2603" }

[colors.primary]
foreground = "#fffbf6"
background = "#21084a"

[colors.normal]
black   = "#000000"
red     = "#ff2603"
green   = "#9be205"
yellow  = "#ffc400"
blue    = "#00a2fa"
magenta = "#815bb5"
cyan    = "#00deef"
white   = "#ffffff"

[colors.bright]
black   = "#565656"
red     = "#ff4250"
green   = "#b8e36e"
yellow  = "#ffd852"
blue    = "#00a6ff"
magenta = "#ac7bf0"
cyan    = "#74fdf3"
white   = "#ffffff"

[cursor]
style = { shape = "Underline", blinking = "Never" }

[terminal]
shell = "/opt/homebrew/bin/tuios"

[keyboard]
bindings = [
  { key = "T",     mods = "Super",         command = { program = "/opt/homebrew/bin/tmux", args = [ "neww" ] } },
  { key = "Tab",   mods = "Control",               command = { program = "/opt/homebrew/bin/tmux", args = [ "next" ] } },
  { key = "Tab",   mods = "Control|Shift",         command = { program = "/opt/homebrew/bin/tmux", args = [ "prev" ] } },
  { key = "Enter", mods = "Super",                 command = { program = "/opt/homebrew/bin/tmux", args = [ "splitw" ] } },
  { key = "L",     mods = "Control|Super",         command = { program = "/opt/homebrew/bin/tmux", args = [ "next-layout" ] } },
  { key = "H",     mods = "Shift|Super",           command = { program = "/opt/homebrew/bin/tmux", args = [ "selectp", "-L" ] } },
  { key = "J",     mods = "Shift|Super",           command = { program = "/opt/homebrew/bin/tmux", args = [ "selectp", "-D" ] } },
  { key = "K",     mods = "Shift|Super",           command = { program = "/opt/homebrew/bin/tmux", args = [ "selectp", "-U" ] } },
  { key = "L",     mods = "Shift|Super",           command = { program = "/opt/homebrew/bin/tmux", args = [ "selectp", "-R" ] } },
  { key = "H",     mods = "Control|Shift|Super",   command = { program = "/opt/homebrew/bin/tmux", args = [ "resizep", "-L" ] } },
  { key = "J",     mods = "Control|Shift|Super",   command = { program = "/opt/homebrew/bin/tmux", args = [ "resizep", "-D" ] } },
  { key = "K",     mods = "Control|Shift|Super",   command = { program = "/opt/homebrew/bin/tmux", args = [ "resizep", "-U" ] } },
  { key = "L",     mods = "Control|Shift|Super",   command = { program = "/opt/homebrew/bin/tmux", args = [ "resizep", "-R" ] } },
  ]
